Add Professor Column and additional schedule
PittCSWiki/pittcswiki pull request #288
Opened 2021-06-25 03:31 UTC by EParmar18

Put each professor listed for each course along with their ratemyprofessor link

2021-07-02 03:46 UTC, Zmwang622 commented on src/guides/academics/scheduling.mdx
> +| CS 1510 - Algorithm Design       |  [Kirk Pruhs](https://www.ratemyprofessors.com/ShowRatings.jsp?tid=105280) |
You'll need to add another column in the table header. Here's info on how to 
![image](https://user-images.githubusercontent.com/36709118/124217563-8f732580-dac6-11eb-9f2a-22f4030b6314.png)

2021-07-02 03:47 UTC, Zmwang622 commented on src/guides/academics/scheduling.mdx
> +| CS 1520 - Programming Language for Web Applications | [Nick Farnan](https://www.ratemyprofessors.com/ShowRatings.jsp?tid=1894664), [Evangelos Karageorgos](https://www.ratemyprofessors.com/ShowRatin
Has Evangelos Karageorgos taught 1520? Can't seem to find it on RMP

2021-07-02 03:48 UTC, Zmwang622 commented on src/guides/academics/scheduling.mdx
>  | **S Tier: Rough**                |
Is this list supposed to be for profs we recommend to take or just the profs in general?

2021-07-02 03:49 UTC, EParmar18 commented on src/guides/academics/scheduling.mdx
> +| CS 1520 - Programming Language for Web Applications | [Nick Farnan](https://www.ratemyprofessors.com/ShowRatings.jsp?tid=1894664), [Evangelos Karageorgos](https://www.ratemyprofessors.com/ShowRatin
On the SCI class page is showed him as the summer prof so I added him to the list

2021-07-02 03:50 UTC, Zmwang622 requested changes
The Markdown format for the table is wrong so fix that and we can see how it looks. Rn the professors aren't rendering on the preview or the netlify preview

2021-07-02 03:51 UTC, Zmwang622 commented
GitHub Preview:
![image](https://user-images.githubusercontent.com/36709118/124217872-23dd8800-dac7-11eb-96d6-c491688e2ca3.png)

Netlify Preview:
![image](https://user-images.githubusercontent.com/36709118/124217938-3bb50c00-dac7-11eb-9391-f75f4be64720.png)

2021-07-02 03:51 UTC, EParmar18 commented on src/guides/academics/scheduling.mdx
>  | **S Tier: Rough**                |
I put all the profs that teach the course, I think it gets hard to recommend profs sometimes because it can be pretty subjective. But we could have it as just profs we recommend

2021-07-02 03:57 UTC, EParmar18 commented on src/guides/academics/scheduling.mdx
> +| CS 1520 - Programming Language for Web Applications | [Nick Farnan](https://www.ratemyprofessors.com/ShowRatings.jsp?tid=1894664), [Evangelos Karageorgos](https://www.ratemyprofessors.com/ShowRatin
http://courses.sci.pitt.edu/courses/view/CS-1520

2021-07-03 15:50 UTC, Zmwang622 commented on src/guides/academics/scheduling.mdx
> +| CS 1520 - Programming Language for Web Applications | [Nick Farnan](https://www.ratemyprofessors.com/ShowRatings.jsp?tid=1894664), [Evangelos Karageorgos](https://www.ratemyprofessors.com/ShowRatin
Oh I think he's listed as a TA

2021-07-05 20:38 UTC, Richie78321 commented
@Zmwang622 You need to reapprove if your requested changes have been made.

2021-07-11 18:40 UTC, Zmwang622 approved these changes

2021-07-30 05:56 UTC, merged