Add three new pages to career guides
PittCSWiki/pittcswiki pull request #297
Opened 2021-07-05 14:45 UTC by sim1029

## Issues linked to this post
- https://github.com/PittCSWiki/pittcswiki/issues/183
- https://github.com/PittCSWiki/pittcswiki/issues/187
- https://github.com/PittCSWiki/pittcswiki/issues/240

### Issue 183
I created a page for freshman / sophomore specific opportunities based on Ming's reddit post: https://old.reddit.com/r/csMajors/comments/htusm4/internships_for_freshmansophomores/fyj59dq/?context=3

### Issue 187
I created a page with links to all the leetcode problems and solutions. 

### Issue 240
I created a page serving as a resume checklist.

2021-07-05 20:50 UTC, Richie78321 requested changes

2021-07-05 20:50 UTC, Richie78321 commented on src/guides/career/study-plan.md
> +- [Sliding Window Max (Bonus)](https://leetcode.com/problems/sliding-window-maximum/)
```suggestion
- [Sliding Window Max (**Bonus**)](https://leetcode.com/problems/sliding-window-maximum/)
```

2021-07-05 20:50 UTC, Richie78321 commented on src/guides/career/study-plan.md
> +- [Find Duplicate Number (**Bonus**)](https://leetcode.com/problems/find-the-duplicate-number/)- [
```suggestion
- [Find Duplicate Number (**Bonus**)](https://leetcode.com/problems/find-the-duplicate-number/)
```

2021-07-05 20:50 UTC, Richie78321 commented on src/guides/career/study-plan.md
> +- [LRU Cache (Bonus)](https://leetcode.com/problems/lru-cache/)
```suggestion
- [LRU Cache (**Bonus**)](https://leetcode.com/problems/lru-cache/)
```

2021-07-05 20:50 UTC, Richie78321 commented on src/guides/career/study-plan.md
> +- [Game of Life (Bonus)](https://youtu.be/YZ-W5DrKPQ0)
super nit, for consistency with sections above, consider making this and below bold as well
```suggestion
- [Game of Life (**Bonus**)](https://youtu.be/YZ-W5DrKPQ0)
```

2021-07-05 20:50 UTC, Richie78321 commented on src/guides/career/study-plan.md
> +#### Week 10 - Graphs
These and below are a smaller header size. Is this intentional?
```suggestion
### Week 10 - Graphs
```

2021-07-05 20:50 UTC, Richie78321 commented on src/guides/career/resume-checklist.md
> +---
I think this guide should be placed within the existing [Crafting your Resume guide](https://pittcs.wiki/career/resume/). Thoughts?

2021-07-05 20:50 UTC, Richie78321 commented on src/guides/career/freshman-sophomore-opportunities.md
> +---
This is great!!! However, I worry about the maintainability of a page like this, as I see some of the links below are subject to change. I wonder if this would be better suited as a separate repository on freshman/sophomore opportunities (or merged with the existing PittCSC internship repo) as a subsection. @Zmwang622 what do you think?

2021-07-05 20:51 UTC, Richie78321 commented
Overall great work. Thanks for putting in the time to do this!

2021-07-05 22:02 UTC, Zmwang622 commented on src/guides/career/resume-checklist.md
> +---
Imo meh. What's nice about putting this guide by itself is that its a quick read for freshmen/sophomores making their resumes for the first time. From what Mat and I found, most people would just skip reading the entire resume guide

2021-07-05 22:03 UTC, Zmwang622 commented on src/guides/career/freshman-sophomore-opportunities.md
> +---
I don't think we could make it a subsection on the internship repo bc it'd look bad. But maybe we just remove the links? they're unnecessary. If people know that these programs exist they can google them themselves. That's what I did.

Also does our link-based unit tests check for dead links?

2021-07-05 22:04 UTC, Zmwang622 commented on src/guides/career/study-plan.md
> +- [Game of Life (Bonus)](https://youtu.be/YZ-W5DrKPQ0)
yeah i got too lazy LOL simon you do it

2021-07-06 15:32 UTC, Richie78321 commented on src/guides/career/freshman-sophomore-opportunities.md
> +---
I'm not sure about the dead links test in this case, but I do like the idea of removing the links and just keeping the names.

2021-07-06 21:17 UTC, Richie78321 approved these changes
Thanks so much for putting this together!

2021-07-06 21:20 UTC, merged