Succeed in 441
PittCSWiki/pittcswiki pull request #306
Opened 2021-07-13 20:40 UTC by dylanfeehan

added a folder in guides/academics/succeed-in-x, where we write guides for how to succeed in certain courses. I started it off with a first draft of how to succeed in 441.

2021-07-13 20:49 UTC, EParmar18 commented
Think you have a small spelling error "This course will focus heavily on the **itegers** (which are discrete by nature), whereas a continuous field like calculus focuses on real numbers"

2021-07-13 20:59 UTC, Zmwang622 requested changes
going to request changes for now, bc i have some comments that ill write later

2021-07-13 21:12 UTC, EParmar18 commented on src/guides/academics/succeed-in-course-x/succeed-in-441.md
> +- If you're *really* stuck, don't look up the answer (especially on a homework, thats cheating). Often times is helpful to step away from a problem or even sleep on it.
"Often times **is** helpful to step away from a problem or even sleep on it." - grammar thing, probably change to it's or it is

2021-07-13 21:15 UTC, EParmar18 commented on src/guides/academics/succeed-in-course-x/succeed-in-441.md
> +- As with most CS courses, avoid rote memorizaiton. Computer science is very a conceptual field and memorization plays a miniscule role. What's important is understanding the systems / patterns, conc
"all of which are skills that can be **strengthented** with practice" - spelled strengthened wrong here

2021-07-13 21:18 UTC, EParmar18 commented on src/guides/academics/succeed-in-course-x/succeed-in-441.md
> +You can learn a *massive* amount of information from this course. You will have better problem solving skills, you'll be better prepared to understand theoretical topics in CS, and your logical think
"I will admit this was a very challenging course. But if you spend enough time engaging with the material, you can and will get very **comfortabile** with it" - spelled comfortable wrong and a grammatical change, probably change it to
  "I will admit this is a challenging course, but if you spend enough time engaging with the material you will succeed!"

2021-07-13 21:19 UTC, EParmar18 commented on src/guides/academics/succeed-in-course-x/succeed-in-441.md
> +You can learn a *massive* amount of information from this course. You will have better problem solving skills, you'll be better prepared to understand theoretical topics in CS, and your logical think
Also spelled ** probably ** wrong

2021-07-14 22:07 UTC, EParmar18 commented on src/guides/academics/succeed-in-course-x/succeed-in-441.md
> +You can learn a *massive* amount of information from this course. You will have better problem solving skills, you'll be better prepared to understand theoretical topics in CS, and your logical think
"it's **probalby** not increasing the value of your education" - probably still spelled wrong

2021-07-18 03:18 UTC, dylanfeehan commented
> going to request changes for now, bc i have some comments that ill write later

yo dude can u just let me in

2021-07-22 06:14 UTC, Zmwang622 commented on src/guides/academics/succeed-in-course-x/succeed-in-441.md
> +  - This is the theoretical foundation of the course which teaches you how to derive additional information from some given information. Thoroughly understanding the proofing techniques is incredibly
I think the content you wrote here is great, but I recommend breaking it down into more bullet points for easier reading.

2021-07-22 06:16 UTC, Zmwang622 commented on src/guides/academics/succeed-in-course-x/succeed-in-441.md
> +- To specify, this section will be about the preparation you can do before the *semester*. Walking into the first day of lecture with a solid understanding of the course material is a fantastic learn
once again we probably shouldn't have a bullet here. Either break it up into multiple bullets or just have it be a paragraph (which I think is better for this specific section)

2021-07-22 06:17 UTC, Zmwang622 commented on src/guides/academics/succeed-in-course-x/succeed-in-441.md
> +- *Discrete Mathematics and its Applications* by Kenneth Rosen is a fantastic textbook. The concepts are explained well and there are in-text exercises to get you ready for the end-of-chapter problem
maybe link to the textbook?

2021-07-22 06:21 UTC, Zmwang622 approved these changes
For the time being this is good, we'll probably turn this guide into a separate course guide when we have more of these sort of stuff written out. 

Please don't merge until you address my other comments though. Main issue is that a list with just one bullet point and long ass paragraph is not a great UX choice (bullets are supposed to drill topics down into atomic snippets).

 For the headers under `How to succeed in 441` (ex: Preparation, Readings, The textbook, Homeworks, Studying), consider just making those paragraphs.  Also consider breaking those large paragraphs into smaller ones. It's just not easy to read a large chunk of text.

2021-07-22 06:24 UTC, Zmwang622 commented on src/guides/academics/succeed-in-course-x/succeed-in-441.md
> +You can learn a *massive* amount of information from this course. You will have better problem solving skills, you'll be better prepared to understand theoretical topics in CS, and your logical think
also you use the word I alot but we don't know who I is. Either add a author tag in the front matter ([example of front matter](https://github.com/PittCSWiki/pittcswiki/blob/ef03b24dd6d58b5e0bce70ead86028d7658fbfff/src/guides/academics/prospective/coe-vs-cs.md)) or change the I's to we's.

2021-07-22 18:55 UTC, dylanfeehan commented on src/guides/academics/succeed-in-course-x/succeed-in-441.md
> +  - This is the theoretical foundation of the course which teaches you how to derive additional information from some given information. Thoroughly understanding the proofing techniques is incredibly
which content? the topics covered or something else?

2021-07-22 19:19 UTC, merged